NotSerializableException: io.jmix.dynattr.impl.DynAttrMetaProperty jmix-framework/jmix#377
Make DynAttrMetaProperty serializable as far as possible in order to make CacheItem fully serializable

(cherry picked from commit 4312248c61fc183f16cd9bab09739a825b3c4a87)