IllegalArgumentException: Can't find setter for property 'commission' at class com.company.untitled1.entity.People jmix-framework/jmix#880
(cherry picked from commit 93c6cb2291d7341de47dc1912c6768f8fd6aa25a)