IllegalArgumentException: Can't find setter for property 'commission'. Rename jmix-framework/jmix#880
(cherry picked from commit b3fcfc82ca93774f25ef5b53804e0caa2c773f00)