NotSerializableException: io.jmix.dynattr.impl.DynAttrMetaProperty. Javadoc jmix-framework/jmix#377
(cherry picked from commit edef7c54a570b4a7544ccb677d082e513e1dd17d)