NotSerializableException: io.jmix.dynattr.impl.DynAttrMetaProperty. Typo jmix-framework/jmix#377
(cherry picked from commit 0414d6f3d98cca804bc428faeb2b9303b42a8ae2)